version: 2

sources:

  - name: purchasing
    schema: purchasing
    tables:
     - name: shipmethod
  - name : humanresources
    schema : humanresources
    tables:
     - name : employee
    

models:
  - name: stg_shipment
    columns:
      - name: shipmethodid
        description: The unique identifier for the shipment method.
        tests:      
          - unique
          - not_null
      - name: transportername
        description: The name of the shipment, method.
      - name: priceship
        description: The base cost of the shipment.
      - name: identifyierunique
        description: number uniquely identifying the record.
      - name: datemodify
        description: The date when the shipment method record was last modified.

  - name : stg_employee
    columns:
      - name: nationalidnumber
        description: The unique identifier for the shipment method.
        tests:      
          - unique
          - not_null
  