version: 2

sources:

  - name: purchasing
    schema: purchasing
    tables:
     - name: shipmethod
     - name : vendor
     - name: productvendor
 
     - name : purchaseorderdetail

     - name: purchaseorderheader

  - name : humanresources
    schema : humanresources
    tables:
     - name : employee
     - name: employeedepartmenthistory
     - name: shift

  - name: person
    tables:
      - name: person
    
  - name: production
    schema : production
    tables:
      - name: product
      - name : productsubcategory
      - name : productmodel

models:
  - name: stg_shipment
    columns:
      - name: shipmethodid
        description: The unique identifier for the shipment method.
        tests:      
          - unique
          - not_null
      - name: transportername
        description: The name of the shipment, method.
      - name: priceship
        description: The base cost of the shipment.
      - name: identifyierunique
        description: number uniquely identifying the record.
      - name: datemodify
        description: The date when the shipment method record was last modified.

  - name : stg_employee
    columns:
      - name: businessentityid
        description: The identifier of the entity business.
      - name : firstname
        description: The first name for each employee
      - name : lastname
        description: The last name for each employee
      - name : nationalidnumber
        description: The nationalidnumber for each employee, the identifier for each employee
        tests:      
          - unique
          - not_null
      - name : gender
        description: The gender for each employee
      - name : name
        description: The name of shift of the employee works
  
  - name : stg_product
    columns:
      - name : productID
        description: "A unique identifier for the product"
      - name: ProductName
        description: "The name of the product"
      - name: productnumber
        description: "The product number"
      - name: safetystocklevel
        description: "Safety stock level"
      - name: reorderpoint
        description: "Reorder point"
      - name: standardcost
        description: "Standard cost"
      - name: listprice
        description: "List price"
      - name: productLine
        description: "Product line"
      - name: class
        description: "Class of the product"
      - name: style
        description: "Style of the product"
      - name: productsubcategoryid
        description: "Product subcategory ID"
      - name: productsubcategoryname
        description: "Name of the product subcategory"
      - name: productcategoryname
        description: "Name of the product category"
      - name: productmodelid
        description: "Product model ID"
      - name: productmodelname
        description: "Name of the product model"

  - name : stg_vendor
    columns:
      - name: VendorID
        description: "A unique identifier for the vendor"
      - name: name
        description: "The name of the vendor"
      - name: creditrating
        description: "The credit rating of the vendor"
      - name: preferredvendorstatus
        description: "Preferred vendor status"
      - name: activeflag
        description: "Indicates whether the vendor is active"
      - name: purchasingwebserviceurl
        description: "The URL of the vendor's purchasing web service"
      - name: minorderqty
        description: "Minimum order quantity"
      - name: maxorderqty
        description: "Maximum order quantity"
      - name: onorderqty
        description: "Quantity currently on order"
      - name: lastreceiptcost
        description: "Cost of the last receipt"
      - name: lastreceiptdate
        description: "Date of the last receipt"
      - name: averageleadtime
        description: "Average lead time for orders"
      - name: productid
        description: "Product ID associated with the vendor"
      - name: productname
        description: "Name of the product associated with the vendor"

  - name : stg_factorder
    columns:
      - name: purchaseorderid
        description: "A unique identifier for the purchase order"
      - name: purchaseorderdetailid
        description: "A unique identifier for the purchase order detail line"
      - name: orderdate
        description: "The date when the order was placed"
      - name: shipdate
        description: "The date when the order was shipped"
      - name: status
        description: "The status of the purchase order"
      - name: vendorid
        description: "A unique identifier for the vendor"
      - name: productid
        description: "A unique identifier for the product"
      - name: orderqty
        description: "The quantity ordered"
      - name: unitprice
        description: "The price per unit"
      - name: receivedqty
        description: "The quantity received"
      - name: rejectedqty
        description: "The quantity rejected"
      - name: shipmethodid
        description: "A unique identifier for the shipping method"
      - name: subtotal
        description: "The subtotal for the purchase order"
      - name: taxamt
        description: "The tax amount for the purchase order"
      - name: freight
        description: "The freight cost for the purchase order"
      - name: modifieddate
        description: "The date when the record was last modified"

  - name: stg_order
    columns:
      - name: purchaseorderid
        description: "A unique identifier for purchase"
        tests:
          - unique
          - not_null
      - name: Vendor_ID
        description: "A unique identifier for the vendor"
        tests:
          - unique
          - not_null
      - name: businessentityid
        description: "A unique identifier for the employees"
        tests:
          - unique
          - not_null
      - name: productID
        description: "A unique identifier for the product"
        tests:
          - unique
          - not_null
      - name: ShipMethodID
        description: "A unique identifier for the shipment company"
        tests:
          - unique
          - not_null
      - name: revisionnumber
        description: "Status of the order"
      - name: orderdate
        description: "Date of the order"
      - name: shipdate
        description: "Date of the delivery"
      - name: subtotal
        description: "Total cost of product."
      - name: taxamt
        description: "Tax of the delivery"
      - name: freight
        description: "cost of the delivery"
      - name: modifieddate
        description: "order change status data"
      