version: 2

sources:

  - name: purchasing
    schema: purchasing
    tables:
     - name: shipmethod

  - name : humanresources
    schema : humanresources
    tables:
     - name : employee
     - name: employeedepartmenthistory
     - name: shift

  - name: person
    tables:
      - name: person

models:
  - name: stg_shipment
    columns:
      - name: shipmethodid
        description: The unique identifier for the shipment method.
        tests:      
          - unique
          - not_null
      - name: transportername
        description: The name of the shipment, method.
      - name: priceship
        description: The base cost of the shipment.
      - name: identifyierunique
        description: number uniquely identifying the record.
      - name: datemodify
        description: The date when the shipment method record was last modified.

  - name : stg_employee
    columns:
      - name: businessentityid
        description: The identifier of the entity business.
      - name : firstname
        description: The first name for each employee
      - name : lastname
        description: The last name for each employee
      - name : nationalidnumber
        description: The nationalidnumber for each employee, the identifier for each employee
        tests:      
          - unique
          - not_null
      - name : gender
        description: The gender for each employee
      - name : name
        description: The name of shift of the employee works
  