version: 2

sources:

  - name: purchasing
    schema: purchasing
    tables:
     - name: shipmethod
    

models:
  - name: stg_shipment
    columns:
      - name: ship_method_id
        description: The unique identifier for the shipment method.
        tests:      
          - unique
          - not_null
      - name: ship_name
        description: The name of the shipment method.
      - name: ship_base
        description: The base cost of the shipment.
      - name: ship_rate
        description: The rate of the shipment.
      - name: modified_date
        description: The date when the shipment method record was last modified.

  

  