version: 2

models:
  - name: dim_date
    description: Date dimension table
  - name: dim_shipment
    description: >
      Dimension table for the shipments. Each record represents the state of
      the shipments between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_shipments
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: shipmethodid
        description: "A unique identifier for the shipment"
      - name: transportername
        description: "The name of transporter company"
      - name: priceship
        description: "The price of the shipments for each transporter company"
      - name: identifyierunique
        description: "Number uniquely identifying the record"
      - name: datemodify
        description: "Date and time the record was last updated"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
  
  - name: dim_employee
    description: >
      Dimension table for the employee. Each record represents the state of
      the employee.
    columns:
      - name: sk_employee
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: businessentityid
        description: "A unique identifier for the business ententy"
      - name: firstname
        description: "The first name of the employee"
      - name: lastname
        description: "The last name of the employee"
      - name: nationalidnumber
        description: "The national number of the employee"
      - name: gender
        description: "The gender of each employee"
      - name : name
        description: "The name of the shift of where employee works"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."

  - name: dim_vendor
    description: >
      Dimension table for the vendors. Each record represents a vendor.
    columns:
      - name: sk_vendor
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: VendorID
        description: "A unique identifier for the vendor"
      - name: name
        description: "The name of the vendor"
      - name: creditrating
        description: "The credit rating of the vendor"
      - name: preferredvendorstatus
        description: "Preferred vendor status"
      - name: activeflag
        description: "Indicates whether the vendor is active"
      - name: purchasingwebserviceurl
        description: "The URL of the vendor's purchasing web service"
      - name: minorderqty
        description: "Minimum order quantity"
      - name: maxorderqty
        description: "Maximum order quantity"
      - name: onorderqty
        description: "Quantity currently on order"
      - name: lastreceiptcost
        description: "Cost of the last receipt"
      - name: lastreceiptdate
        description: "Date of the last receipt"
      - name: averageleadtime
        description: "Average lead time for orders"
      - name: productid
        description: "Product ID associated with the vendor"
      - name: productname
        description: "Name of the product associated with the vendor"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
