version: 2

models:
  - name: dim_date
    description: Date dimension table
  - name: dim_shipment
    description: >
      Dimension table for the shipments. Each record represents the state of
      the shipments between the dates `valid_from` and `valid_to`.
    columns:
      - name: sk_shipments
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: shipmethodid
        description: "A unique identifier for the shipment"
      - name: transportername
        description: "The name of transporter company"
      - name: priceship
        description: "The price of the shipments for each transporter company"
      - name: identifyierunique
        description: "Number uniquely identifying the record"
      - name: datemodify
        description: "Date and time the record was last updated"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."